m3(|file:///|)[
  @declarations={
    <|php+class:///y|,|file:///Users/ruud/git/php-analysis/src/tests/resources/m3/class001.php|(49,57,<7,0>,<7,0>)>,
    <|php+method:///x/getx|,|file:///Users/ruud/git/php-analysis/src/tests/resources/m3/class001.php|(20,25,<4,0>,<4,0>)>,
    <|php+class:///x|,|file:///Users/ruud/git/php-analysis/src/tests/resources/m3/class001.php|(8,39,<3,0>,<3,0>)>,
    <|php+method:///y/gety|,|file:///Users/ruud/git/php-analysis/src/tests/resources/m3/class001.php|(72,32,<8,0>,<8,0>)>
  },
  @containment={
    <|php+class:///y|,|php+method:///y/gety|>,
    <|php+class:///x|,|php+method:///x/getx|>,
    <|php+namespace:///|,|php+class:///x|>,
    <|php+namespace:///|,|php+class:///y|>
  },
  @modifiers={
    <|php+class:///y|,abstract()>,
    <|php+method:///y/gety|,abstract()>,
    <|php+method:///y/gety|,public()>,
    <|php+method:///x/getx|,public()>
  },
  @uses={}
]