m3(|file:///|)[
  @declarations={
    <|php+class:///x|,|file:///Users/ruud/git/php-analysis/src/tests/resources/m3/variable_method_call001.php|(8,165,<3,0>,<3,0>)>,
    <|php+field:///x/prop|,|file:///Users/ruud/git/php-analysis/src/tests/resources/m3/variable_method_call001.php|(29,11,<5,0>,<5,0>)>,
    <|php+method:///x/tostring|,|file:///Users/ruud/git/php-analysis/src/tests/resources/m3/variable_method_call001.php|(51,58,<7,0>,<7,0>)>,
    <|php+method:///x/getclass|,|file:///Users/ruud/git/php-analysis/src/tests/resources/m3/variable_method_call001.php|(115,56,<11,0>,<11,0>)>,
    <|php+globalVar:///x|,|file:///Users/ruud/git/php-analysis/src/tests/resources/m3/variable_method_call001.php|(174,2,<15,0>,<15,0>)>,
    <|php+globalVar:///a|,|file:///Users/ruud/git/php-analysis/src/tests/resources/m3/variable_method_call001.php|(184,2,<16,0>,<16,0>)>,
    <|php+globalVar:///x|,|file:///Users/ruud/git/php-analysis/src/tests/resources/m3/variable_method_call001.php|(214,2,<19,0>,<19,0>)>,
    <|php+globalVar:///x|,|file:///Users/ruud/git/php-analysis/src/tests/resources/m3/variable_method_call001.php|(229,2,<20,0>,<20,0>)>,
    <|php+globalVar:///a|,|file:///Users/ruud/git/php-analysis/src/tests/resources/m3/variable_method_call001.php|(252,2,<21,0>,<21,0>)>,
    <|php+globalVar:///ts|,|file:///Users/ruud/git/php-analysis/src/tests/resources/m3/variable_method_call001.php|(265,3,<23,0>,<23,0>)>
  },
  @uses= {
    <|file:///Users/ruud/git/php-analysis/src/tests/resources/m3/variable_method_call001.php|(159,5,<12,0>,<12,0>),|php+class:///x|>,
    <|file:///Users/ruud/git/php-analysis/src/tests/resources/m3/variable_method_call001.php|(193,2,<16,0>,<16,0>),|php+globalVar:///x|>,
    <|file:///Users/ruud/git/php-analysis/src/tests/resources/m3/variable_method_call001.php|(197,2,<17,0>,<17,0>),|php+globalVar:///a|>,
    <|file:///Users/ruud/git/php-analysis/src/tests/resources/m3/variable_method_call001.php|(219,2,<19,0>,<19,0>),|php+globalVar:///a|>,
    <|file:///Users/ruud/git/php-analysis/src/tests/resources/m3/variable_method_call001.php|(234,2,<20,0>,<20,0>),|php+globalVar:///a|>,
  	<|file:///Users/ruud/git/php-analysis/src/tests/resources/m3/variable_method_call001.php|(260,2,<21,0>,<21,0>),|php+globalVar:///b|>,
    <|file:///Users/ruud/git/php-analysis/src/tests/resources/m3/variable_method_call001.php|(283,2,<24,0>,<24,0>),|php+globalVar:///a|>,
    <|file:///Users/ruud/git/php-analysis/src/tests/resources/m3/variable_method_call001.php|(299,3,<24,0>,<24,0>),|php+globalVar:///ts|>
  },
  @modifiers={
    <|php+method:///x/tostring|,public()>,
    <|php+method:///x/getclass|,public()>,
    <|php+field:///x/prop|,public()>
  }
]